[package]
edition = "2018"
name = "examples"
publish = false
version = "0.0.0"

[dev-dependencies]
piped = {path = "../piped"}
reqwest = "0.11.3"
tokio = {version = "1.5.0", features = ["macros", "rt-multi-thread"]}

[[example]]
name = "channel"
path = "channel.rs"
